<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, http } from '@/api/http'
import type { Category, PageData, Product } from '@/types'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'

const tab=ref('products'),loading=ref(false),keyword=ref(''),products=ref<Product[]>([]),categories=ref<Category[]>([]),total=ref(0),page=ref(1),dialog=ref(false),categoryDialog=ref(false),editing=ref<number|null>(null),uploading=ref(false)
const product=reactive<any>({code:'',barcode:'',name:'',categoryId:null,specification:'',unit:'件',purchasePrice:0,salePrice:0,imageUrl:'',status:'ON_SALE',lowStockThreshold:10})
const category=reactive<any>({name:'',code:'',sortOrder:0,status:'ENABLED'})
async function load(){loading.value=true;try{if(tab.value==='products'){const d=await api<PageData<Product>>(http.get('/catalog/products',{params:{keyword:keyword.value,page:page.value,pageSize:15}}));products.value=d.items;total.value=d.total}else{const d=await api<PageData<Category>>(http.get('/catalog/categories',{params:{keyword:keyword.value,page:page.value,pageSize:15}}));categories.value=d.items;total.value=d.total}}finally{loading.value=false}}
async function loadCategories(){const d=await api<PageData<Category>>(http.get('/catalog/categories',{params:{pageSize:100}}));categories.value=d.items}
function newProduct(){editing.value=null;Object.assign(product,{code:'',barcode:'',name:'',categoryId:categories.value[0]?.id||null,specification:'',unit:'件',purchasePrice:0,salePrice:0,imageUrl:'',status:'ON_SALE',lowStockThreshold:10});dialog.value=true}
function editProduct(row:Product){editing.value=row.id;Object.assign(product,row);dialog.value=true}
async function saveProduct(){if(!product.code||!product.barcode||!product.name||!product.categoryId){ElMessage.warning('请填写编码、条码、名称和分类');return}const req=editing.value?http.put(`/catalog/products/${editing.value}`,product):http.post('/catalog/products',product);await api(req);ElMessage.success('商品已保存');dialog.value=false;load()}
async function uploadImage(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;uploading.value=true;try{const form=new FormData();form.append('file',file);const d=await api<{url:string}>(http.post('/catalog/products/images',form));product.imageUrl=d.url;ElMessage.success('图片上传成功')}finally{uploading.value=false}}
function newCategory(){editing.value=null;Object.assign(category,{name:'',code:'',sortOrder:0,status:'ENABLED'});categoryDialog.value=true}
function editCategory(row:Category){editing.value=row.id;Object.assign(category,row);categoryDialog.value=true}
async function saveCategory(){if(!category.name||!category.code){ElMessage.warning('请填写分类名称和编码');return}const req=editing.value?http.put(`/catalog/categories/${editing.value}`,category):http.post('/catalog/categories',category);await api(req);ElMessage.success('分类已保存');categoryDialog.value=false;load();loadCategories()}
async function removeCategory(row:Category){await ElMessageBox.confirm(`确认删除分类“${row.name}”？已有商品关联时后端会拒绝。`,'删除分类',{type:'warning'});await api(http.delete(`/catalog/categories/${row.id}`));ElMessage.success('已删除');load()}
onMounted(async()=>{await loadCategories();await load()})
</script>
<template><div><div class="page-head"><div><h2>商品与分类</h2><p>编码、条码保持唯一；历史订单保存成交时快照。</p></div><el-button type="primary" :icon="Plus" @click="tab==='products'?newProduct():newCategory()">新增{{ tab==='products'?'商品':'分类' }}</el-button></div><section class="panel"><el-tabs v-model="tab" @tab-change="page=1;keyword='';load()"><el-tab-pane label="商品档案" name="products"/><el-tab-pane label="商品分类" name="categories"/></el-tabs><div class="toolbar"><el-input v-model="keyword" clearable placeholder="名称、编码或条码" style="width:300px" @keyup.enter="page=1;load()"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-button @click="page=1;load()">查询</el-button></div><el-table v-if="tab==='products'" v-loading="loading" :data="products" stripe><el-table-column prop="code" label="商品编码" width="120"/><el-table-column prop="barcode" label="条码" width="150"/><el-table-column prop="name" label="商品" min-width="150"><template #default="s"><div style="display:flex;gap:10px;align-items:center"><el-image v-if="s.row.imageUrl" :src="s.row.imageUrl" fit="cover" style="width:38px;height:38px;border-radius:8px"/><strong>{{ s.row.name }}</strong></div></template></el-table-column><el-table-column prop="categoryName" label="分类" width="110"/><el-table-column prop="specification" label="规格" width="120"/><el-table-column label="采购 / 售价" width="150"><template #default="s">¥{{ s.row.purchasePrice }} / <strong>¥{{ s.row.salePrice }}</strong></template></el-table-column><el-table-column label="可售库存" width="100"><template #default="s"><span :class="s.row.availableQty<=s.row.lowStockThreshold?'danger-text':'stock-ok'">{{ s.row.availableQty }}</span></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='ON_SALE'?'success':'info'">{{ s.row.status==='ON_SALE'?'在售':'下架' }}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link type="primary" @click="editProduct(s.row)">编辑</el-button></template></el-table-column></el-table><el-table v-else v-loading="loading" :data="categories" stripe><el-table-column prop="code" label="分类编码"/><el-table-column prop="name" label="分类名称"/><el-table-column prop="sortOrder" label="排序" width="100"/><el-table-column prop="productCount" label="商品数" width="100"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.status==='ENABLED'?'success':'info'">{{ s.row.status==='ENABLED'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="editCategory(s.row)">编辑</el-button><el-button link type="danger" @click="removeCategory(s.row)">删除</el-button></template></el-table-column></el-table><el-pagination style="margin-top:18px;justify-content:flex-end" background layout="total,prev,pager,next" :total="total" :page-size="15" v-model:current-page="page" @current-change="load"/></section>
<el-dialog v-model="dialog" :title="editing?'编辑商品':'新增商品'" width="680px"><el-form label-position="top"><div class="form-grid"><el-form-item label="商品编码" required><el-input v-model="product.code" maxlength="40"/></el-form-item><el-form-item label="条码" required><el-input v-model="product.barcode" maxlength="64"/></el-form-item><el-form-item label="商品名称" required><el-input v-model="product.name" maxlength="120"/></el-form-item><el-form-item label="分类" required><el-select v-model="product.categoryId" style="width:100%"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="规格"><el-input v-model="product.specification"/></el-form-item><el-form-item label="单位" required><el-input v-model="product.unit"/></el-form-item><el-form-item label="采购价"><el-input-number v-model="product.purchasePrice" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="销售价"><el-input-number v-model="product.salePrice" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="低库存阈值"><el-input-number v-model="product.lowStockThreshold" :min="0" style="width:100%"/></el-form-item><el-form-item label="销售状态"><el-select v-model="product.status" style="width:100%"><el-option label="在售" value="ON_SALE"/><el-option label="下架" value="OFF_SALE"/></el-select></el-form-item></div><el-form-item label="商品图片"><div style="display:flex;align-items:center;gap:12px"><el-image v-if="product.imageUrl" :src="product.imageUrl" style="width:72px;height:72px;border-radius:10px" fit="cover"/><label class="el-button"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden @change="uploadImage">{{ uploading?'上传中…':'选择图片' }}</label></div></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="saveProduct">保存</el-button></template></el-dialog>
<el-dialog v-model="categoryDialog" :title="editing?'编辑分类':'新增分类'" width="480px"><el-form label-position="top"><el-form-item label="分类名称" required><el-input v-model="category.name"/></el-form-item><el-form-item label="分类编码" required><el-input v-model="category.code" placeholder="例如 FRESH_FOOD"/></el-form-item><el-form-item label="排序"><el-input-number v-model="category.sortOrder" :min="0"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="category.status"><el-radio-button value="ENABLED">启用</el-radio-button><el-radio-button value="DISABLED">停用</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="categoryDialog=false">取消</el-button><el-button type="primary" @click="saveCategory">保存</el-button></template></el-dialog></div></template>
