<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api,http } from '@/api/http'
import type { PageData,Product } from '@/types'
import { ElMessage } from 'element-plus'
import { Close } from '@element-plus/icons-vue'
const products=ref<Product[]>([]),cart=ref<Array<Product&{quantity:number}>>([]),keyword=ref(''),barcode=ref(''),loading=ref(false),paymentMethod=ref('CASH'),receipt=ref<any>(),receiptDialog=ref(false)
const total=computed(()=>cart.value.reduce((s,x)=>s+x.salePrice*x.quantity,0))
async function search(){loading.value=true;try{const d=await api<PageData<Product>>(http.get('/catalog/products',{params:{keyword:keyword.value,pageSize:30}}));products.value=d.items.filter(x=>x.status==='ON_SALE')}finally{loading.value=false}}
async function scan(){if(!barcode.value)return;try{const p=await api<Product>(http.get(`/catalog/products/barcode/${encodeURIComponent(barcode.value)}`));add(p);barcode.value=''}catch{barcode.value=''}}
function add(p:Product){const found=cart.value.find(x=>x.id===p.id);if(found){if(found.quantity>=p.availableQty){ElMessage.warning('已达到可售库存');return}found.quantity++}else{if(p.availableQty<1){ElMessage.warning('商品无可售库存');return}cart.value.push({...p,quantity:1})}}
function clamp(row:Product&{quantity:number}){if(row.quantity>row.availableQty){row.quantity=row.availableQty;ElMessage.warning('数量已按可售库存调整')}}
async function checkout(){if(!cart.value.length)return;loading.value=true;try{receipt.value=await api(http.post('/orders',{idempotencyKey:crypto.randomUUID(),channel:'WEB_POS',autoPay:true,paymentMethod:paymentMethod.value,items:cart.value.map(x=>({productId:x.id,quantity:x.quantity}))}));receiptDialog.value=true;cart.value=[];await search();ElMessage.success('模拟收款成功，库存已扣减')}finally{loading.value=false}}
onMounted(search)
</script>
<template><div><div class="page-head"><div><h2>Web 收银台</h2><p>搜索或扫描条码加入清单，结算后生成销售单与库存流水。</p></div><div class="notice">到店付款 / 模拟收款，不接入真实资金交易</div></div><div class="cart-layout"><section class="panel"><div class="toolbar"><el-input v-model="barcode" placeholder="扫描或输入条码后回车" style="width:300px" @keyup.enter="scan"><template #prefix><el-icon><FullScreen/></el-icon></template></el-input><el-input v-model="keyword" clearable placeholder="搜索商品名称或编码" style="width:280px" @keyup.enter="search"/><el-button @click="search">查找</el-button></div><div v-loading="loading" class="product-cards"><article v-for="p in products" :key="p.id" class="product-card" @click="add(p)"><h4>{{ p.name }}</h4><p>{{ p.code }} · {{ p.specification||'标准规格' }}</p><p>可售 {{ p.availableQty }} {{ p.unit }}</p><strong>¥{{ Number(p.salePrice).toFixed(2) }}</strong></article></div></section><aside class="panel cart-panel"><div class="page-head"><div><h2>本次清单</h2><p>{{ cart.length }} 种商品</p></div><el-button v-if="cart.length" text type="danger" @click="cart=[]">清空</el-button></div><div v-if="!cart.length" class="empty-state"><el-icon size="42"><ShoppingCart/></el-icon><p>从左侧选择商品</p></div><div v-for="row in cart" :key="row.id" class="cart-row"><div><strong>{{ row.name }}</strong><div style="font-size:13px;color:var(--muted);margin-top:4px">¥{{ row.salePrice }} / {{ row.unit }}</div></div><div style="display:flex;align-items:center;gap:5px"><el-input-number v-model="row.quantity" :min="1" :max="row.availableQty" size="small" @change="clamp(row)"/><el-button circle text :icon="Close" @click="cart.splice(cart.indexOf(row),1)"/></div></div><template v-if="cart.length"><div class="cart-total"><span>应收合计</span><strong>¥{{ total.toFixed(2) }}</strong></div><el-select v-model="paymentMethod" style="width:100%;margin-bottom:12px"><el-option label="现金（模拟）" value="CASH"/><el-option label="银行卡（模拟）" value="CARD"/><el-option label="移动支付（模拟）" value="MOBILE"/></el-select><el-button type="primary" size="large" style="width:100%" :loading="loading" @click="checkout">确认模拟收款</el-button></template></aside></div><el-dialog v-model="receiptDialog" title="收款完成" width="500px"><el-result icon="success" title="模拟收款成功" :sub-title="`销售单号：${receipt?.orderNo||''}`"><template #extra><div class="notice">本次未发生真实资金交易</div><h2>实收 ¥{{ Number(receipt?.paidAmount||0).toFixed(2) }}</h2></template></el-result></el-dialog></div></template>
