<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api,http } from '@/api/http'
import type { PageData,Supplier } from '@/types'
import { ElMessage,ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
const list=ref<Supplier[]>([]),total=ref(0),page=ref(1),keyword=ref(''),loading=ref(false),dialog=ref(false),editing=ref<number|null>(null)
const form=reactive<any>({code:'',name:'',contactName:'',phone:'',email:'',address:'',status:'ENABLED',remark:''})
async function load(){loading.value=true;try{const d=await api<PageData<Supplier>>(http.get('/suppliers',{params:{keyword:keyword.value,page:page.value,pageSize:15}}));list.value=d.items;total.value=d.total}finally{loading.value=false}}
function open(row?:Supplier){editing.value=row?.id||null;Object.assign(form,row||{code:'',name:'',contactName:'',phone:'',email:'',address:'',status:'ENABLED',remark:''});dialog.value=true}
async function save(){if(!form.code||!form.name){ElMessage.warning('请填写供应商编码和名称');return}await api(editing.value?http.put(`/suppliers/${editing.value}`,form):http.post('/suppliers',form));ElMessage.success('供应商已保存');dialog.value=false;load()}
async function remove(row:Supplier){await ElMessageBox.confirm(`确认删除“${row.name}”？存在采购记录时不能删除。`,'删除供应商',{type:'warning'});await api(http.delete(`/suppliers/${row.id}`));ElMessage.success('已删除');load()}
onMounted(load)
</script>
<template><div><div class="page-head"><div><h2>供应商资料</h2><p>维护联系人、联系方式和合作状态。</p></div><el-button type="primary" :icon="Plus" @click="open()">新增供应商</el-button></div><section class="panel"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="名称、编码或联系人" style="width:300px" @keyup.enter="page=1;load()"/><el-button @click="page=1;load()">查询</el-button></div><el-table v-loading="loading" :data="list" stripe><el-table-column prop="code" label="编码" width="120"/><el-table-column prop="name" label="供应商" min-width="180"/><el-table-column prop="contactName" label="联系人" width="110"/><el-table-column prop="phone" label="电话" width="140"/><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column prop="address" label="地址" min-width="220" show-overflow-tooltip/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='ENABLED'?'success':'info'">{{ s.row.status==='ENABLED'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><el-pagination style="margin-top:18px;justify-content:flex-end" background layout="total,prev,pager,next" :total="total" :page-size="15" v-model:current-page="page" @current-change="load"/></section><el-dialog v-model="dialog" :title="editing?'编辑供应商':'新增供应商'" width="640px"><el-form label-position="top"><div class="form-grid"><el-form-item label="供应商编码" required><el-input v-model="form.code"/></el-form-item><el-form-item label="供应商名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="联系人"><el-input v-model="form.contactName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item></div><el-form-item label="地址"><el-input v-model="form.address"/></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
