<script setup lang="ts">
import { ref } from 'vue'
import { onPullDownRefresh,onShow } from '@dcloudio/uni-app'
import { assetUrl,request,token,user } from '@/api/http'
import { addCart } from '@/stores/cart'
const categories=ref<any[]>([]),products=ref<any[]>([]),categoryId=ref<number|undefined>(),keyword=ref(''),loading=ref(false),canShop=ref(true)
async function load(){canShop.value=!token()||user()?.role==='MEMBER';loading.value=true;try{const query=`keyword=${encodeURIComponent(keyword.value)}&pageSize=50${categoryId.value===undefined?'':`&categoryId=${categoryId.value}`}`;const [c,p]=await Promise.all([request<any[]>('/catalog/public/categories'),request<any>(`/catalog/public/products?${query}`)]);categories.value=c;products.value=p.items.map((item:any)=>({...item,imageUrl:assetUrl(item.imageUrl)}))}finally{loading.value=false;uni.stopPullDownRefresh()}}
function choose(id?:number){categoryId.value=id;load()}
onShow(load);onPullDownRefresh(load)
</script>
<template><view class="page"><view class="row" style="margin-bottom:22rpx"><view><view class="title">今日好物</view><view class="subtitle" style="margin:0">库存与后台实时同步</view></view><view class="tag">{{ canShop?'到店付款':'员工浏览' }}</view></view><view v-if="!canShop" class="notice" style="margin-bottom:20rpx">员工账号仅用于业务查询，购买请登录普通会员账号。</view><view class="row"><input v-model="keyword" class="input" style="flex:1;margin-bottom:18rpx" placeholder="搜索商品、编码或条码" confirm-type="search" @confirm="load"/><button class="primary" size="mini" @click="load">搜索</button></view><scroll-view scroll-x style="white-space:nowrap;margin-bottom:20rpx"><view class="tag" :style="!categoryId?'background:#0b6b57;color:white':''" style="margin-right:14rpx" @click="choose()">全部</view><view v-for="c in categories" :key="c.id" class="tag" :style="categoryId===c.id?'background:#0b6b57;color:white':''" style="margin-right:14rpx" @click="choose(c.id)">{{ c.name }}</view></scroll-view><view v-if="!products.length&&!loading" class="empty">暂无匹配商品</view><view v-for="p in products" :key="p.id" class="card product" @click="uni.navigateTo({url:`/pages/product/detail?id=${p.id}`})"><image v-if="p.imageUrl" class="product-image" :src="p.imageUrl" mode="aspectFill"/><view v-else class="product-image" style="display:flex;align-items:center;justify-content:center;color:#0b6b57;font-size:54rpx;font-weight:800">青</view><view class="product-info"><view class="product-name">{{ p.name }}</view><view class="muted">{{ p.specification||'标准规格' }} · 可售 {{ p.availableQty }} {{ p.unit }}</view><view class="row" style="margin-top:16rpx"><view class="price">¥{{ Number(p.salePrice).toFixed(2) }}</view><button v-if="canShop" class="primary" size="mini" :disabled="p.availableQty<1" @click.stop="addCart(p)">加入</button></view></view></view></view></template>
